### ISSUE TITLE
How to re-order colors

### ISSUE THREAD

**Issue by zach-is-my-name** [azabiong/vim-highlighter#4]
Hi, 

It's not clear to me from reading the documentation how to re-order the colors. Can you please help me out?

**Comment by azabiong** [comment]
Hi zach,
Thanks for your interest in this plugin.

As you know, each preset color has a number, and is applied to words in order by default. And you can also give the color number using number keys before setting, like `7` `HiSet` for brown color.

Reordering colors is relatively easier than editing the colors with adjustments. If you have a list of colors, you may only need to change the color numbers.

To get the color list and change the numbers, and finally save and load them, the following steps may be useful.

- First, open a new file, and type any word and then highlight that word. This will fully load the plugin.
- In the command window, enter the `hi` command
```vim
    : hi
```
- After some scrolling down, you can probably find the `HiColor` list. 
- Using mouse drag, select the `HiColor` list, copy and paste it to the current empty file.
```
   HiColor1       xxx ctermfg=17 ctermbg=113 guifg=#001767 guibg=#8fd757
   HiColor2       xxx ctermfg=52 ctermbg=221 guifg=#570000 guibg=#fcd757
```
- If you delete the `xxx` keyword and add the `hi` command at the beginning, each line will be a complete vim command that you can run right in the command window.
```vim
   hi HiColor1  ctermfg=17 ctermbg=113 guifg=#001767 guibg=#8fd757
   hi HiColor2  ctermfg=52 ctermbg=221 guifg=#570000 guibg=#fcd757
```
- You can now change color numbers and try it in the command window using copy and paste.
- If you notice that the colors have changed, I would recommend that you move on to the next step rather than changing the entire color right now.
- Save the current file with a `.vim` extension, for example `my_color.vim`
- Move the file into your `~/.vim/colors` directory (or `~/vimfiles/colors` on Windows)
- Let’s see if we can load `my_color` using vim command. Enter `colo<tab><tab>` in the command window
```vim
    : colo<Tab><Tab>
```
- If it works, yes, you can now open your color scheme file `my_color` at any time, edit or add new colors.
- Finally add a command to automatically load your colors in the bottom part of your configuration file.
 ```vim
   colorscheme my_color
```

**Comment by zach-is-my-name** [comment]
Thank you.  The rest of the documentation seemed clear and this feels like a solid plugin for a wonderful use-case.  Next time I need to use the feature, I'll reference this to get the effect I'm looking for

**Comment by azabiong** [comment]
Nice, I hope this tool helps. Please let me know if you need any other feature.
Thank you
